dataset:
  zju_mocap_path: ../../data/zju
  subject: '377'
  sex: neutral
views:
- 0
- 6
- 12
- 18
start_end:
- 0
- 300
output:
  dir: ../../dataset/zju_mocap/standard/377
  name: 377_train
interval: 1
