dataset:
  zju_mocap_path: ../../data/zju
  subject: '394'
  sex: neutral
views:
- 0
- 6
- 12
- 18
start_end:
- 0
- 300
output:
  dir: ../../dataset/zju_mocap/standard/394
  name: 394_train
interval: 1
